theme = "native"
icons = "awesome"

[[block]]
block = "net"
device = "wlo1"
format = " {speed_down;K*B}"
interval = 0.1


[[block]]
block = "net"
device = "wlx200db042033a"
format = " {speed_down;K*B}"
interval = 0.1
[[block]]
block = "cpu"
interval = 0.2


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}({mem_used_percents})"
# format_swap = "{SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = " %d/%m %R"

[[block]]
block = "battery"
interval = 0.1
format = "{percentage}"
